/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package bankUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Uglybear
 */
public class bankLogin extends javax.swing.JFrame {
    
    
    private String customerLastName = "", customerPin = "", customerName = "";
    Connection connection = null;
    String lastName = "", firstName = "";
    double currentBalance = 0.0;
    
    /**
     * Creates new form bankLogin
     */
    public bankLogin() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lastNameEntry = new javax.swing.JFormattedTextField();
        pinNumberLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        buttonContinue = new javax.swing.JButton();
        bankNameLabel = new javax.swing.JLabel();
        pinNumberEntry = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pinNumberLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pinNumberLabel.setText("Pin Number (16 Digits)");

        lastNameLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lastNameLabel.setText("Last Name");

        buttonContinue.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        buttonContinue.setText("Continue");
        buttonContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContinueActionPerformed(evt);
            }
        });

        bankNameLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        bankNameLabel.setText("Bank Name");

        pinNumberEntry.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.##"))));
        pinNumberEntry.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        pinNumberEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinNumberEntryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bankNameLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameLabel)
                            .addComponent(pinNumberLabel)
                            .addComponent(lastNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pinNumberEntry))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonContinue)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bankNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lastNameLabel)
                .addGap(18, 18, 18)
                .addComponent(lastNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pinNumberLabel)
                .addGap(18, 18, 18)
                .addComponent(pinNumberEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonContinue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    public void sendDetails()
    {
        bankUI mainInterface = new bankUI();
        mainInterface.setCustomerPinNumber(customerPin);
        mainInterface.setCustomerName(customerName);
        mainInterface.setCustomerBalance(currentBalance);
        
        mainInterface.setVisible(true);
        this.dispose();
    }
    
    private void buttonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContinueActionPerformed
        
        customerPin = pinNumberEntry.getText();
        customerLastName = lastNameEntry.getText();
        
        
        // Check of empty input
        if (customerPin.equals("") && customerLastName.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter in your last name and 16 digit pin number", "Error", JOptionPane.ERROR_MESSAGE);
        }
        // Check if pin is of correct length or is a number
        else if (customerPin.length() != 16 || !customerPin.matches("^\\d+"))
        {
            pinNumberEntry.setText("");
            JOptionPane.showMessageDialog(null, "Please enter in your 16 digit pin number", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        { 
            try
            {
                String connect_url = "jdbc:sqlite:customerDetails.db";
                connection = DriverManager.getConnection(connect_url);
                
                java.sql.Statement statement = connection.createStatement();
                java.sql.ResultSet resultSet;

                resultSet = statement.executeQuery("SELECT CustomerFirstName, CustomerLastName, CustomerBalance FROM Customers WHERE CustomerPinNumber = " + customerPin);

                while ( resultSet.next() )
                {
                    lastName = resultSet.getString("CustomerLastName");
                    firstName = resultSet.getString("CustomerFirstName");
                    currentBalance = resultSet.getDouble("CustomerBalance");
                }

                connection.close();
                
                if ( lastName.equals("") )
                {
                    lastNameEntry.setText("");
                    pinNumberEntry.setText("");
                    JOptionPane.showMessageDialog(null, "Please enter in your last name or your 16 digit pin number", "Error", JOptionPane.ERROR_MESSAGE);
                }
                else if (customerLastName.equals(lastName))
                {
                    customerName = firstName + " " + lastName;
                    sendDetails();
                }
                else
                {
                    lastNameEntry.setText("");
                    JOptionPane.showMessageDialog(null, "Please enter in your last name", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch (SQLException e)
            {
                e.printStackTrace();
            }
            
            
        }
    }//GEN-LAST:event_buttonContinueActionPerformed

    private void pinNumberEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinNumberEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinNumberEntryActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bankLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bankLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bankLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bankLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bankLogin().setVisible(true);
            }
        });
    }
    
    
    public void connectDB()
    {
        
        
        try {
            //String connect_url = "jdbc:sqlite:C:/SQLite/customerDetails.db";
            String connect_url = "jdbc:sqlite:customerDetails.db";
            connection = DriverManager.getConnection(connect_url);
            //System.out.println("Successfully connected to SQLite database..");
        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bankNameLabel;
    private javax.swing.JButton buttonContinue;
    private javax.swing.JFormattedTextField lastNameEntry;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JFormattedTextField pinNumberEntry;
    private javax.swing.JLabel pinNumberLabel;
    // End of variables declaration//GEN-END:variables
}
