/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Uglybear
 */
public class transferUI extends javax.swing.JFrame {

    String currentPin = "", currentName = "", targetPin = "";
    double currentBalance = 0.0;
    Connection connection = null;
    
    /**
     * Creates new form transferUI
     */
    public transferUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountLabel = new javax.swing.JLabel();
        buttonTransfer = new javax.swing.JButton();
        transferLabel = new javax.swing.JLabel();
        amountEntry = new javax.swing.JFormattedTextField();
        toEntry = new javax.swing.JFormattedTextField();
        toLabel = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        amountLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        amountLabel.setText("Amount");

        buttonTransfer.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        buttonTransfer.setText("Transfer");
        buttonTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTransferActionPerformed(evt);
            }
        });

        transferLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        transferLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transferLabel.setText("Transfer");

        toLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        toLabel.setText("To");

        buttonBack.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toEntry)
                            .addComponent(amountEntry)
                            .addComponent(amountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(transferLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonTransfer)))
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toLabel)
                .addGap(18, 18, 18)
                .addComponent(toEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(amountLabel)
                .addGap(18, 18, 18)
                .addComponent(amountEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBack)
                    .addComponent(buttonTransfer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setCustomerPinNumber(String pinNumber)
    {
        this.currentPin = pinNumber;
    }
    
    public void setCustomerName(String name)
    {
        this.currentName = name;
    }
    
    public void setCustomerBalance (double balance)
    {
        this.currentBalance = balance;
    }
    
    private void buttonTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTransferActionPerformed

        
        String to = toEntry.getText();
        String amount = amountEntry.getText();

        // Check of empty input
        if (to.equals("") && amount.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter the target account pin number and the amount to transfer.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        // Check if pin is of correct length or is a number
        else if (to.length() != 16 || !to.matches("^\\d+"))
        {
            toEntry.setText("");
            JOptionPane.showMessageDialog(null, "Please enter a valid target 16 digit pin number", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if (amount.matches(("^\\d")))
        {
            JOptionPane.showMessageDialog(null, "Please enter a valid transfer amount", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try
            {
                String connect_url = "jdbc:sqlite:customerDetails.db";
                connection = DriverManager.getConnection(connect_url);

                java.sql.Statement statement = connection.createStatement();
                java.sql.ResultSet resultSet;

                resultSet = statement.executeQuery("SELECT CustomerID FROM Customers WHERE CustomerPinNumber = " + to);

                while ( resultSet.next() )
                {
                    targetPin = resultSet.getString("CustomerID");
                }

                if ( targetPin.equals("") )
                {
                    toEntry.setText("");
                    JOptionPane.showMessageDialog(null, "Please enter a valid target 16 digit pin number", "Error", JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    if (currentBalance < Double.parseDouble(amount))
                    {
                        JOptionPane.showMessageDialog(null, "You do not have enough money in your account to make that transfer.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    else
                    {
                        statement.executeUpdate("UPDATE Customers SET CustomerBalance = CustomerBalance + " + amount + " WHERE CustomerPinNumber = " + to);
                        statement.executeUpdate("UPDATE Customers SET CustomerBalance = CustomerBalance - " + amount + " WHERE CustomerPinNumber = " + currentPin);
                        
                        currentBalance = currentBalance - Double.parseDouble(amount);
                        
                        connection.close();
                        
                        JOptionPane.showMessageDialog(null, "Transfer Successful. " + "Remaining balance: " + currentBalance);
                        
                        bankUI mainInterface = new bankUI();
                        mainInterface.setCustomerPinNumber(currentPin);
                        mainInterface.setCustomerName(currentName);
                        mainInterface.setCustomerBalance(currentBalance);
        
                        mainInterface.setVisible(true);
                        this.dispose();
                    }

                }

                

            }
            catch (SQLException e)
            {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_buttonTransferActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        bankUI mainInterface = new bankUI();
        mainInterface.setCustomerPinNumber(currentPin);
        mainInterface.setCustomerName(currentName);
        mainInterface.setCustomerBalance(currentBalance);
        
        mainInterface.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transferUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transferUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transferUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transferUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transferUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField amountEntry;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonTransfer;
    private javax.swing.JFormattedTextField toEntry;
    private javax.swing.JLabel toLabel;
    private javax.swing.JLabel transferLabel;
    // End of variables declaration//GEN-END:variables
}
